version: "3"

services:
  influxdb:
    restart: unless-stopped
    image: influxdb:1.8
    build:
      context: ./
      args:
        branch: 1.8
    ports:
      - "8086:8086"
    expose:
      - "8086"
    volumes:
      # - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      # - HOST_PROC=/host/proc
